### ISSUE TITLE
Can't install on mac os

### ISSUE THREAD

**Issue by demidovakatya** [Songbee/desktop#12]
![electron doesn't want to work](https://cloud.githubusercontent.com/assets/5788652/21782204/ac74d126-d6c3-11e6-8c7b-4eb9a81c457f.jpg)

And if I run `./node_modules/.bin/electron .`:
![photo_2017-01-09_23-30-24](https://cloud.githubusercontent.com/assets/5788652/21782194/a271857a-d6c3-11e6-8960-30843b5cdc71.jpg)

Would also be awesome if you update the instructions afterwards.

_translated by @iamale_

**Comment by notpushkin** [comment]
@demidovakatya Looks like it's time for me to ~~try Hackintosh again~~ grab a Mac somewhere

**Comment by notpushkin** [comment]
@demidovakatya Have you had a chance to try the updated instructions?

**Comment by demidovakatya** [comment]
okay, I'm installing:
```
git clone https://github.com/Songbee/desktop songbee
cd songbee 
npm install && gulp && npm run build && npm start
``` 

aaand I get this error
```
zsh: command not found: gulp
```

Could you please add a couple of lines about prerequisites and how to install them? :3

**Comment by reo7sp** [comment]
@demidovakatya try running just `npm install && npm run build && npm start`

**Comment by notpushkin** [comment]
@demidovakatya Yeah, the `gulp` step is extraneous, it is basically replaced with `npm run build` now.

(Under the hood, it still runs `gulp`, it just doesn't require it to be installed globally anymore)

**Comment by demidovakatya** [comment]
Oh...
![](https://cloud.githubusercontent.com/assets/5788652/22578897/23a7aa94-e9dd-11e6-988b-807afd0a6c3c.png)

**Comment by demidovakatya** [comment]
Sorry for silly questions – I know nothing about `gulp`/`npm`/etc. 😳 

Now I have to understand how to use it, I gues...

**Comment by notpushkin** [comment]
@demidovakatya Glad it started working for you!

To actually play something, you can get a .torrent-file somewhere and drag-and-drop it to the app window — the in-app browsing and search are still in works.
