### ISSUE TITLE
copyright waiver page doesn't exist

### ISSUE THREAD

**Issue by ungoldman** [Songbee/desktop#4]
When going to https://www.clahub.com/agreements/Songbee/desktop to look at the copyright waiver as instructed in [CONTRIBUTING.md](https://github.com/Songbee/desktop/blob/master/CONTRIBUTING.md), I get a 404.

> The page you were looking for doesn't exist.
> 
> You may have mistyped the address or the page may have moved.

**Comment by notpushkin** [comment]
@ungoldman Nice catch. I was trying out various services like [CLAHub](https://www.clahub.com/) and the [CLA assistant](https://cla-assistant.io/) and think we'll stick with the latter — I'll set it up later today and update CONTRIBUTING.md accordingly. Thank you!

**Comment by notpushkin** [comment]
@ungoldman I've set up the CLA Assistant integration. Maybe you could help try it out by sending some PR? :)

**Comment by ungoldman** [comment]
*maybe I will*
