### ISSUE TITLE
Test it on Windows and macOS

### ISSUE THREAD

**Issue by notpushkin** [Songbee/desktop#5]
Especially Windows since the mpv [IPC socket interface](https://mpv.io/manual/master/#json-ipc) might not work or work differently there.

> #nowplaying Galantis — Runaway (U & I) (Dillon Francis Remix)

**Comment by notpushkin** [comment]
~~I guess it also needs some docs on how to actually install and run it (i. e. hints on how to install mpv)~~ added to the README

**Comment by j-holub** [comment]
I have also thought about making the Node-MPV API Windows compatible. MPV itself works with Windows over IPC as far as I know.

I don't have any Windows installation to test it though.

**Comment by notpushkin** [comment]
@reo7sp reports it works fine on Mac, hooray!

@00SteinsGate00 I'm going to toy with it in a Windows VM today, from what I see in docs it might work as-is.

**Comment by notpushkin** [comment]
@00SteinsGate00 It works! You just have to set `socket` option to Windows-style `\\.\pipe\somename` (don't forget to escape the backslashes, i. e. `"\\\\.\\pipe\\somename"`).

**Comment by notpushkin** [comment]
For some reason though the build from https://mpv.srsfckn.biz/ plays audio about 1.5x faster for me .-.

(UPD: Maybe it's some VM quirks though; — https://sourceforge.net/projects/mpv-player-windows/files builds behave the same way.)

**Comment by j-holub** [comment]
@iamale That's cool. I have to see if node can actually find out what OS it's running on and make a default fallback to Windows Style, if it's running on Windows.

One thing to note is, that I haven't found out yet at which version MPV introduced the ipc socket stuff yet. When you run Debian and install it from the package manager, you get a very very very old MPV version 0.6, which does not work with the IPC stuff.
The dependencies to build mpv on Debian are too old as well, but there is a nice build script from the mpv guys, that builds everything required to build mpv and builds mpv itself. It can be found [here](https://github.com/mpv-player/mpv-build).

**Comment by notpushkin** [comment]
Everything works fine on Windows 7! Except that `[::]` should be changed to `localhost` as it for some reason doesn't understand IPv6 I guess.

@00SteinsGate00 The easiest way IMO would be just to bundle mpv with the app (that in fact is what I'm planning to do with Windows/OS X; not sure if this violates GPL, though).

The earliest version should be 0.7.0, according to [this commit](https://github.com/mpv-player/mpv/commit/e0f0f6fe26b7f8d941a20f2c86564b83e5fb52cb). The problem, however, is that mpv [uses versions only for Linux distributions](https://github.com/mpv-player/mpv/blob/master/DOCS/release-policy.md), so on other platforms it can't be used to detect IPC support (or [flags to work with it](https://github.com/00SteinsGate00/Node-MPV/blob/c04a3761821ec9476ec1ba7e30a03ddc47ea6856/lib/mpv/mpv.js#L39)).

For example, here's how the latest mpv's `--version` output looks on Windows:

```
mpv git-1a2319f (C) 2000-2016 mpv/MPlayer/mplayer2 projects
built on Sat Nov 26 05:11:08 MYT 2016
ffmpeg library versions:
libavutil 55.41.101
libavcodec 57.66.107
libavformat 57.58.101
libswscale 4.3.101
libavfilter 6.67.100
libswresample 2.4.100
ffmpeg version: N-44543-g711c5f3
```

Not sure about OS X, though. @reo7sp, can you give me a hand here?

> #nowplaying CAZZETTE — The Rat

**Comment by j-holub** [comment]
I have a version number on OS X here as well. The point is, that if you self compile a version from a non-release commit, you will get the commit hash as the version number on Linux / OS X, too.

But that is basically covered in my Node-MPV module.

I just wanna add something to the readme like "MPV Version 0.7 or higher required". Using `process.platform` in node.js provides you the operating system (*darwin*, *win32*, *linux* and so on). I considder adding this to my package to change the default socket for Windows.

**Comment by notpushkin** [comment]
@00SteinsGate00 How about an option to provide a socket name and convert it depending on a platform? I. e. `socket_name: "songbee-mpv"` would result in `\\.\pipe\songbee-mpv` on Windows and `/tmp/songbee-mpv.sock` on *nix.
