### ISSUE TITLE
Add a normal icon

### ISSUE THREAD

**Issue by notpushkin** [Songbee/desktop#9]
I've made some [programmer art][] for now:

![Current icon](https://cloud.githubusercontent.com/assets/1298948/20868302/d98f3480-ba71-11e6-8750-f540ac733099.png)

[programmer art]: https://en.wikipedia.org/wiki/Programmer_art

**Comment by notpushkin** [comment]
(In case you're wondering, 'bee~!' is actually [bee][], a frequent commenter on The Tor Blog. He signs as `~bee!!!!!!` and his comments generally look like that:

> Hi!!!!!!!!
>
> Well, i ain't very sure about the headline!!! I think that it could be cool to have a new bit-torrent application made to work with TOR!!! You could even call it "TORrent"!!! It's very easy!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

His style is silly (probably to hide his identity), but his ideas are wise. This icon is actually kind of a tribute to him.)

[bee]: https://blog.torproject.org/blog/bittorrent-over-tor-isnt-good-idea#comment-5509

**Comment by notpushkin** [comment]
Here are some thoughts:

![screenshot_2017-01-05_01-51-55](https://cloud.githubusercontent.com/assets/1298948/21662232/17786e7c-d2f2-11e6-82d5-2bd5d4cfa698.png)

**Comment by reo7sp** [comment]
Songbee core's icon is cool
